targets:
  $default:
    builders:
      json_serializable:
        options:
          create_factory: true
          create_field_map: false
          create_json_keys: false
          create_per_field_to_json: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          include_if_null: true
