name: sources
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  injectable: ^2.5.0
  get_it: ^8.0.2
  json_annotation: ^4.9.0
  mysql_client: ^0.0.27
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  lints: ^4.0.0
  test: ^1.24.0
